### ISSUE TITLE
SaverSample Failed

### ISSUE THREAD

**Issue by bishinew** [OneDrive/onedrive-picker-android#10] opened 2016-02-07 19:41 UTC
Download the sample and run it. Generates the following error message:

Error during upload

Sorry, there was a problem

Please help.

![device-2016-02-07-130512](https://cloud.githubusercontent.com/assets/3579886/12874739/5f612d86-cd9f-11e5-89cc-f7c36de442e6.png)

**Comment by peternied** [comment] 2016-02-08 06:22
The saver should have received an exception response, do you know which [SaverError](https://github.com/OneDrive/onedrive-picker-android/blob/master/OneDriveSDK/src/com/microsoft/onedrivesdk/saver/SaverError.java#L31) was recieved, or do you have the logcat during that event?

**Comment by bishinew** [comment] 2016-02-08 14:42
I am puzzling why I didn't see any log for this. Should I turn on something?

**Comment by peternied** [comment] 2016-02-08 17:58
When you hit close and are placed back into the SaverExample application there should be a more detailed error description.

**Comment by bishinew** [comment] 2016-02-08 20:29
When I use your example, I didn't get error message. I looked at the logic, it didn't pick up a local file. Instead it just write some letters and save it in the OneDrive.

When I implement the same logic in my app, I got.

Did not get a file from a picker. 

(not sure why I got this message even though I used the Saver logic)

**Comment by peternied** [comment] 2016-02-08 21:46
Is `onActivityResult(...)` getting called in your application?  I would expect you to receive a callback with a more detailed error message.

 Could you provide the code that you are using to invoke the saver?

**Comment by bishinew** [comment] 2016-02-08 22:47
1. The problem for me is that your original explorer project is not working for me. Not sure what I did wrong. Exception at this line

            mSaver.handleSave(requestCode, resultCode, data);

Result: Failure
Error Type: Unknown
Debug Error: Generic Error

2. In my own code.

I got the exception at this line too

			boolean isSaved = mSaver.handleSave(requestCode, resultCode, data);
		
Here is how I called the saver
mUpload.setOnClickListener(new View.OnClickListener() {
			public void onClick(View v) {

				File file = getDatabasePath(ExpenseConstants.DATABASE_NAME);
				if (file == null || !file.isFile()) {
					Toast.makeText(myApp, myApp.getResources().getString(R.string.import_no_file), Toast.LENGTH_LONG).show();
					return;
				}

				// Start the saver
				String filename = ExpenseUtil.covertDateLongToStr((new Date()).getTime(), "yyyy-MM-dd") + ".db";
			
				mSaver.startSaving(OneDrive.this, filename, Uri.fromFile(file));

			}
		});

**Comment by peternied** [comment] 2016-02-09 17:44
When the SaverException is thrown could you get the value of the errorType and the debugErrorInfo when this error occurs?

**Comment by bishinew** [comment] 2016-02-09 18:18
Result: Failure
Error Type: Unknown
Debug Error: Generic Error

**Comment by peternied** [comment] 2016-02-10 17:58
When you get the Uri.fromFile(getDatabasePath(ExpenseConstants.DATABASE_NAME)), is this file/path accessible by other process than your own?

**Comment by bishinew** [comment] 2016-02-10 19:00
Yes. 

Let's make thing simple. Please don't worry about my code.

Right now I have problem to run your explorer example. Please help me run through. 

Exception at this line

    mSaver.handleSave(requestCode, resultCode, data);

Result: Failure
Error Type: Unknown
Debug Error: Generic Error

Thanks

**Comment by bishinew** [comment] 2016-02-10 19:26
Does the sdk version mismatch?  My OneDrive app version is 3.8.

**Comment by bishinew** [comment] 2016-02-14 02:48
Hi

Do you think we did something wrong? We cannot move forward. Not sure how to debug this thing Please advise.

Thanks

**Comment by peternied** [comment] 2016-02-16 21:28
@bishinew Sorry for the delay.

First, could provide me with the application id that you used with the saver (Was it just the sample ID, or did you use your own)?

Lets make sure we get a clear baseline by checking my assumptions:
1. What kind of account are you signed in with? An Microsoft Account, or a AAD Account?
2. Where is the path for the location you were attempting to save file to relative to your drive root?
3. If you open up the OneDrive application, can you upload a file into the same location that you were attempting to save into?
4. If you use the saver with another path does that work?

If you could try to clear the application data for OneDrive, does that affect what happens when you use the saver?

Once I have this information back, I should be able to start resolving this issue.

**Comment by bishinew** [comment] 2016-02-16 21:48
I download the sample and ran it. It's the Sample ID. 

1. We created an Microsoft account. But we ran your sample and use your Sample ID.
2. I read your sample code. It programmatically writes some string into the stream and upload it to one drive. It doesn't load the local file.
3.  If I use the OneDrive, I can save local file into OneDrive any place I created.
4. I tried the saver with another path. It doesn't work for me.

To be clear, I had the problem to run the sample I downloaded from Github. I don't know what I did wrong.

**Comment by peternied** [comment] 2016-02-16 23:40
Thanks for the details, I'm going to investigate and get back when i have details from the service requests.

**Comment by peternied** [comment] 2016-02-17 22:35
@bishinew I could not track down any events from our service side, but there are client side logs that you could collect off your device and send for me to parse.  Please email me the logs you've collected to me at pnied @ microsoft . com and I will unpack what is going.

Please reproduce the issue one more time, then Navigate to `/sdcard/data/com.microsoft.onedrive.skydrive/cache` and copy the entire `instrumentation` folder.  Zip up all the files that file tree and send them to me.

**Comment by sdkcarlos** [comment] 2016-05-10 09:45
@peternied  I can confirm that, my own implementation fails too although everything seems to be in order and the file exists. 

In the saver example, the file gets created but i get the same screen that @bishinew and my own implementation too.

I'm using Android 6.0 (maybe is something about lolipop or >= versions [marshmallow]?) and the error description doesn't show anything useful but : 

![screenshot_20160510-113729](https://cloud.githubusercontent.com/assets/11634719/15142187/39c77cbc-16a4-11e6-8d81-8a1b301c33e2.png)

I'm working in a cordova implementation of this, but it doesn't work. I would be glad if you could help with this issue , my class is here [SaveClass](https://github.com/sdkcarlos/cordova-ourcodeworld-onedrive-filepicker/blob/master/src/android/DialogSaveFile.java).

The file indeed exists as `CouldNotAccessFile` or `NoFileSpecified` only are called if a give a wrong name. GenericError and UnknowError, that's all i get.

**Comment by daboxu** [comment] 2016-05-18 23:24
hi @sdkcarlos , can you send me a sample cordova project which uses your plugin? The picker works fine with my test device so I am not sure if it is related to the picker itself or it is related to cordova framework.

**Comment by yanbli** [comment] 2016-05-24 08:10
I have the same issue above android 6.0 if I don't grant the "Storage" permission for OneDrive app.
If I grant that permission, it can work.

**Comment by hanselip** [comment] 2016-05-24 23:52
@bishinew, @yanbli identified an issue (see: https://github.com/OneDrive/onedrive-picker-android/issues/16) which will be resolved in the next release. You may be hitting this error due to storage permissions not being granted to the OneDrive app. The next release should roll out within 1-2 weeks but as a temporary workaround could you try granting OneDrive storage permissions and then retrying your scenario?

**Comment by yanbli** [comment] 2016-05-30 11:17
@hanselip do you fix this issue? When can I get the sdk which fixed this issue?

**Comment by hanselip** [comment] 2016-06-01 18:50
Hi @yanbli, the fix will actually be a part of the next OneDrive app update which has just started rolling out now. Look for OneDrive version 4.2 which contains the fix.

**Comment by peternied** [comment] 2016-10-31 23:24
I believe this issue has been fixed for a while now, please reopen if this is still a problem with the latest version of the OneDrive client for Android.

**Closed by peternied** 2016-10-31 23:24 UTC
